### ISSUE TITLE
Compatibility with Symphony 5?

### ISSUE THREAD

**Issue by jnweiger** [privacyidea/privacyidea-owncloud-app#102]
Not sure if this applies to privacyidea, please check:

With the upcoming ownCloud 10.13.0  release, we  upgraded from symfony 4 to symfony 5. This required changes in many of our apps.
Details and examples what was done in the apps
 * https://github.com/owncloud/core/issues/39630

Prerelease tar (rc 1)
* https://download.owncloud.com/server/testing/owncloud-complete-20230816.tar.bz2
* https://download.owncloud.com/server/testing/owncloud-10.13.0-rc.1.tar.bz2
* docker run --rm -ti -p 8080:8080 -d owncloud/server:10.13.0-rc.1

**Comment by nilsbehlen** [comment]
Thanks for the information. We will look at this.

**Comment by lukasmatusiewicz** [comment]
Compatible
