### ISSUE TITLE
Issues with trigger-challenge

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea-owncloud-app#105]
If a challenge is triggered but the user does not have a challenge-response token, the response from privacyIDEA is empty:
```
HTTP/1.0 200 OK
Cache-Control: no-cache
Content-Length: 835
Content-Type: application/json
Date: Wed, 01 Nov 2023 11:01:29 GMT
Server: Werkzeug/1.0.1 Python/3.10.11

{
    "detail": {
        "messages": [],
        "multi_challenge": [],
        "threadid": 140605124495040,
        "transaction_ids": []
    },
    "id": 2,
    "jsonrpc": "2.0",
    "result": {
        "authentication": "REJECT",
        "status": true,
        "value": 0
    },
    "signature": "rsa_sha256_pss:52f...560",
    "time": 1698836489.800917,
    "version": "privacyIDEA 3.10.dev1",
    "versionnumber": "3.10.dev1"
}
```
After the response is processed, we run into this code:
https://github.com/privacyidea/privacyidea-owncloud-app/blob/ba7aad8ad64d41032c380222a84f6cadeaf6c0de/twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php#L402
But the `detail->message` does not exist in the response. Could that explain the behaviour?

**Comment by lukasmatusiewicz** [comment]
We can skip this if the message is empty, but maybe it will be good, to set some message like: "0 challenges triggered", or: "The user has no token".

**Comment by gpappsoft** [comment]
Because the message is shown to end users, IMHO it would be better to show something like "You do not have a vaild token". To inform the user that he has no token is maybe a security issue (because of the information by itself).

**Comment by nilsbehlen** [comment]
The message should be defined in privacyidea, even if it is a default one like in this case. The plugins only display the message that is returned from privacyidea without any additional logic
