### ISSUE TITLE
Avoid autosaving passwords in config

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-owncloud-app#11]
When using a browser like firefox and having the login data stored in the browser the following happens:

Administrator goes to config page of privacyidea and changes *anything* but the credentials of the challege-user, data is autosaved.
But: The browser also entered the saved credentials in the challenge user fields.

I am not quite sure, what we should do here, if html parameters are sufficient to avoid this or if we need to change the identifier or names of the fields or if we need to disable the owncloud typical autosave.

**Comment by cornelinux** [comment]
Currently we see no sensible way on solving this issue without breaking the owncloud design.

But we should add a display like "saving configuration" and "configuration saved" when the configuration was saved (like it is done in owncloud's own configuration).

**Comment by fredreichbier** [comment]
should probably use ``autocomplete=new-password``: https://stackoverflow.com/a/43784451

https://github.com/owncloud/core/pull/9575

**Comment by fredreichbier** [comment]
Funny: It's actually enough if the admin has stored the credentials of the owncloud login page and just *visits* the privacyIDEA app page, navigates away and visits it again. The current credentials are overwirrten.

**Comment by cornelinux** [comment]
...this is our way to educate the admin to not store his passwords in the browser! ;-)
