### ISSUE TITLE
Add a test thingy to the configuration tab

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-owncloud-app#17]
In the configuration dialog for the privacyIDEA App, we should add a test dialog like

    enter username: _____________
    enter password and or OTP, which would be sent to privacyIDEA: ____________
    [ TEST IT ]

This way we can at least test the connection and the single shot authentication. I am not sure, if we need to test the challenge response with this setting.

Well, we could have a second test button to actually test, if the credentials of the challenge response user are allowed to trigger a challenge in privacyIDEA.
So in this case a simple second testbutton would be enough:

    [ TEST CHALLENGE RESPONSE ADMIN USER ]

**Comment by fredreichbier** [comment]
[17/test-connection](https://github.com/NetKnights-GmbH/privacyidea-owncloud-app/tree/17/test-connection) now implements a simple "test authentication" functionality in the admin panel. Open points:
* We should probably define a timeout, as Guzzle waits forever by default (?) http://docs.guzzlephp.org/en/5.3/clients.html#timeout
* If we merge #19, we even get somewhat nice error messages :) (like ``"Failed to authenticate. cURL error 60: SSL certificate problem: self signed certificate"``)
* Checking the CR user credentials is still TODO
