### ISSUE TITLE
Error message is not correctly displayed in the 2FA login mask

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea-owncloud-app#18]
Current master on ownCloud 10:

If we enter a wrong OTP value, the error message is always "An error occurred while verifying the token", even though ``verifyChallenge`` returns more specific error messages. This is because this check: https://github.com/NetKnights-GmbH/privacyidea-owncloud-app/blob/1c8c65ecbcbc57709fcfced75789e1fac4c3c5db/twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php#L305
always fails, as it should apparently be
```php
        if (class_exists('OCP\Authentication\TwoFactorAuth\TwoFactorException')) {
```
(see [here](http://de2.php.net/manual/de/function.class-exists.php#82086))

**Comment by cornelinux** [comment]
Oh, this might be a remnant from the time when the 2FAException was not contained in owncloud.
