### ISSUE TITLE
Translate settings panel template and JavaScript

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea-owncloud-app#25]
Just an idea: For ownCloud 10, it is possible to mark strings in templates and JavaScript files for translation: https://doc.owncloud.org/server/latest/developer_manual/app/advanced/l10n.html#templates

We might have a fully localized admin panel then :)

**Comment by cornelinux** [comment]
Should we add this to version 2.4?

**Comment by fredreichbier** [comment]
Not sure :) adding this in 2.4 would only have an advantage if we can also have some translated strings (e.g. German) in 2.4, I guess? Probably boils down to the question how quickly we want to release 2.4.

**Comment by cornelinux** [comment]
I think this is closed with f4e326f2fba903db8ce73e6d3130ea6ebe3c2f65
