### ISSUE TITLE
Use PassOnNoToken from privacyIDEA

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-owncloud-app#27]
We should check in function ``isTwoFactorAuthEnabledForUser`` if the user needs 2FA as defined in privacyIDEA. Since we do not have the user's password available, we can not check for a passthru policy. 

So we use the ``PassOnNoToken`` policy in privacyIDEA.

If the config checkbox setting of our app "Check for PassOnNoToken in privacyIDEA" is activated and if the app is activated, we check with an arbitrary or empty password using the ``$this->authenticate`` method. If the user has no token (and in privacyIDEA PassOnNoToken is configued) the authentication will succeed. The ``isTwoFactorAuthEnabledForUser`` needs to return ``false``.

**Comment by fredreichbier** [comment]
Sounds like a useful feature! But in case the user has a token, wouldn't this increase the failcounter?

**Comment by Mipronimo** [comment]
It will, so we have to add a comment like "Do not activate, if you are not sure" or something like this. It would be just a problem, if the fail limit is 3 or less.
