### ISSUE TITLE
Comments on challenge response

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-owncloud-app#5]
## private functions

I think this could be a private function?

https://github.com/NetKnights-GmbH/privacyidea-owncloud-app/blob/challenge-response/twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php#L234

Also the ``getBaseUrl``?

## raising exceptions

The TriggerChallengeException is always raised:
https://github.com/NetKnights-GmbH/privacyidea-owncloud-app/blob/challenge-response/twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php#L136
I think we should only raise the exception, if we catch another exception. So this should be move to the ``catch``-branch.

The same here:
https://github.com/NetKnights-GmbH/privacyidea-owncloud-app/blob/challenge-response/twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php#L260
It does no harm since it would display an empty string. But I think we should not raise it, if there is no error.

## naming

I think we should change "administrator" to "service account".
https://github.com/NetKnights-GmbH/privacyidea-owncloud-app/blob/challenge-response/twofactor_privacyidea/templates/settings-admin.php#L55

This implies that they should create an extra account with reduced rights for this.

**Comment by fredreichbier** [comment]
## private functions

>I think this could be a private function?
>Also the ``getBaseUrl``?

Definitely! Changed in 9492f7c.

## raising exceptions

Exceptions should hopefully only be raised in case of error -- for the successful, there is a (deeply nested) "return" statement :-)

## naming

>I think we should change "administrator" to "service account".

Done in 2ad2d459.
