### ISSUE TITLE
Couldn't get plugin to Authenticate

### ISSUE THREAD

**Issue by kevdogg** [privacyidea/privacyidea-owncloud-app#6]
Thanks for all the hard work

Managed to get the privacyidea authentication server up and running and could verify the authentication token through the web interface of the app.

Installed Owncloud app, and could never get login to authenticate with token.  In addition page kept trying to refresh likely every 5 seconds on firefox.   

What can I provide to debug this issue?

**Comment by cornelinux** [comment]
The first step always is to take a look at the audit log.
How many tokens have you enrolled in privacyIDEA?

You need a subscription file to run the privacyIDEA ownCloud App with more than 5 tokens. But you will see corresponding log entries in the audit log.

You first need to verify, if the configuration is correct and the owncloud server reaches your privacyIDEA server. Then, when you see the request in the privacyIDEA audit log, you can follow this guide.
https://www.privacyidea.org/getting-help/
