### ISSUE TITLE
Adding requirements

### ISSUE THREAD

**Issue by Mipronimo** [privacyidea/privacyidea-owncloud-app#60]
For the new version we should add something like "You should use privacyIDEA 3.0 or higher" in [README.md](https://github.com/privacyidea/privacyidea-owncloud-app/blob/master/README.md) and [info.xml](https://github.com/privacyidea/privacyidea-owncloud-app/blob/master/twofactor_privacyidea/appinfo/info.xml). Else the push token and triggerchallenge may not work correctly.

**Comment by tamaro-skaljic** [comment]
'Cause this https://github.com/privacyidea/privacyidea/issues/1723 (security) and this https://github.com/privacyidea/privacyidea/issues/1689 (performance) issues we must adding requirements for version 3.1.
