### ISSUE TITLE
The /token/challenges response does spamming

### ISSUE THREAD

**Issue by tamaro-skaljic** [privacyidea/privacyidea-owncloud-app#63]
If we do a /token/challenges response 'cause a push (or in future tiqr) token was enrolled to the user, the process will spamming in the audit log during the persistent check.
Also we currently check by doing a Ajax request to the frontend of /owncloud/index.php/login/challenge/privacyidea and search for a hidden input field that doesn't appear if the checking response in the backend of this page was true, that costs a bunch of traffic.

A better way is to outsource the authentication process for /token/challenge responses and retrieve as a result only a 0 or 1 to trigger the page reload, here we can also fix the audit log spamming by removing the appropriate lines of code.

**Comment by Mipronimo** [comment]
> A better way is to outsource the authentication process for /token/challenge responses and retrieve as a result only a 0 or 1 to trigger the page reload,

If ajax reloads the page, we could set a parameter e.g. `?piAjaxRequest=1`.
In `TwoFactorPrivacyIDEAProvider::getTemplate()` we could add something like
```PHP
// pseudocode incoming
if isset ajaxRequest {
  $template = new Template('ajaxResponse', 'challenge');
  return $template;
}
```

**Comment by Mipronimo** [comment]
Okay in fact my idea does not really help.
If we reduce the template, we still load the theme (with background, etc)

**Comment by Mipronimo** [comment]
I think, we can close this issue.
The Ajax request does not load too much and the audit log should be filled with these messages. So it is not a bug, but a feature. :smile: 
What do you think @cornelinux?

**Comment by cornelinux** [comment]
Filling the audit log is actully a feature.

However, I think there are two things mixed up, if I understand correctly?

1. Fetching the state of the responses (which is fine, works as designed=
2. Sending a request to the owncloud frontend?

**Comment by tamaro-skaljic** [comment]
@Mipronimo I've begun working for a fix which is now online at the branch [Create AJAX Endpoint](https://github.com/privacyidea/privacyidea-owncloud-app/tree/create_ajax_endpoint).
My idea is to define a php-function that you call with ajax over an OwnCloud route, but unfortunately I haven't finished this.

I think @fredreichbier or @NuvandaPV could complete this someday.

Further links to that topic which may help in the future:
[OwnCloud -> Development Environment](https://doc.owncloud.org/server/10.0/developer_manual/app/tutorial/development_environment.html)
[OwnCloud -> Controllers](https://doc.owncloud.org/server/10.0/developer_manual/app/fundamentals/controllers.html)
[OwnCloud -> Routes and Controllers](https://doc.owncloud.org/server/10.0/developer_manual/app/tutorial/routes_and_controllers.html)

@cornelinux Yes, currently we call the OwnCloud-Frontend with ajax requests and I can't recognize where the OwnCloud-Frontend call the authenticate-function from our privacyIdeaProvider...

**Comment by cornelinux** [comment]
To my understanding this will be irrelevant with #76.

**Comment by tamaro-skaljic** [comment]
> To my understanding this will be irrelevant with #76.

Sounds correct.
