### ISSUE TITLE
Allow users to *not* use 2FA

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-owncloud-app#7]
The privacyIDEA ownCloud App could check, if the user needs to provide a 2nd factor.

There several different ways to do this.
First we should plan, how we would want to do this, using which method in the App class.

Obviously the App should ask privacyIDEA (with the service account), if the user has a token and if the setting is allowed. We could also run a *first try* to authenticate the user with *anything*.

This would work if the user had no token and the *passOnNoToken* was configured.

**Comment by cornelinux** [comment]
Another way would be, to configure in the privacyIDEA ownCloud App a comma separated list of usernames, who do not need to provide a 2nd factor.

**Comment by cornelinux** [comment]
@fredreichbier We definitively need the following.
If a guest user is created, then a normal user wants to share data with this guest user. This guest user is not contained in the LDAP directory and thus definitevely not in privacyIDEA.

A newly created guest user is member of the group "guests" or "guest app".

So I think we should allow to configure a list of owncloud groups, where the users do not need 2FA.
If the guest user logs in, there should be no authentication request against privacyIDEA.

(The plugin does not work with challenge response an PassOnNoUser)

**Comment by cornelinux** [comment]
In our app we can configure a simle list of groups, that do *not* need a 2nd factor with privacyIDEA.

We could enhance the function ``isTwoFactorAuthEnabledForUser`` in ``lib/Provider/TwoFactorPrivacyIDEAProvider.php`` using ``isInGroup`` (see https://doc.owncloud.org/api/classes/OCP.IGroupManager.html#method_isInGroup)

If the user is found in any of the configured groups, we can return *false*.

**Comment by cornelinux** [comment]
@fredreichbier Please check, why the user is not found in the group.
https://central.owncloud.org/t/oc-readonly-not-registered-with-guest-app-oc10-0-3/10458

**Comment by fredreichbier** [comment]
Hmm, the group exclusion feature works for me on the current master (456d4e81da0268f44354dbe2908d6ad467886d69), even in conjunction with the guests app. I *do* get messages like the following in the log:
<pre>
{"reqId":"QaAR2fDxhmveiEuGBeLz","level":2,"time":"2017-12-21T13:55:41+00:00","remoteAddr":"192.168.33.1","user":"herbert@example.com","app":"filesystem","method":"GET","url":"\/owncloud\/index.php\/apps\/guests\/whitelist","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"LrcWiRCukYZGeQOB6VQK","level":2,"time":"2017-12-21T13:55:41+00:00","remoteAddr":"192.168.33.1","user":"herbert@example.com","app":"filesystem","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"Wk4NOUuLUZN2HIrl1gLG","level":2,"time":"2017-12-21T13:55:41+00:00","remoteAddr":"192.168.33.1","user":"herbert@example.com","app":"filesystem","method":"GET","url":"\/owncloud\/index.php\/avatar\/herbert%40example.com\/28","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"kicI4bCNsWtTkPbXhTc5","level":2,"time":"2017-12-21T13:55:41+00:00","remoteAddr":"192.168.33.1","user":"herbert@example.com","app":"filesystem","method":"GET","url":"\/owncloud\/index.php\/avatar\/herbert%40example.com\/28","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"rXihc2VI56xnYPHIJifj","level":2,"time":"2017-12-21T13:55:41+00:00","remoteAddr":"192.168.33.1","user":"herbert@example.com","app":"filesystem","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"HW7LRQAulxUEydn50W7V","level":2,"time":"2017-12-21T14:00:41+00:00","remoteAddr":"192.168.33.1","user":"herbert@example.com","app":"filesystem","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
</pre>
but they're also present if I deactivate the ``twofactor_privacyidea`` app.

**Comment by cornelinux** [comment]
I successfully tested this with ownCloud 10.0.7.
Thus I am closing this ticket.
