### ISSUE TITLE
About 2FA and WebDAV

### ISSUE THREAD

**Issue by tanzhenchao** [privacyidea/privacyidea-owncloud-app#80]
2FA plug-in has been enabled, how to authenticate users through WebDAV protocol?
How to call the API?

**Comment by plettich** [comment]
Hi,
in general ownCloud handles the complete authentication, You should not need to call the privacyIDEA API.
If Your WebDAV client support OpenID-Connect or OAuth2 (and it is enabled in ownCloud) this should work directly. Otherwise You might need to create special app passwords for WebDAV.
