### ISSUE TITLE
Login Button out of center allignment

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-owncloud-app#87]
In the latest version 3.0 in our ownCloud installation the "Login" button is somehow out of allignment:

![image](https://user-images.githubusercontent.com/1908620/152115468-de6acf4b-5e8b-47d0-a779-4da84d90fe5a.png)

**Comment by cornelinux** [comment]
This is the code.

Probably some missing main CSS, since the input password field contains a distinct *style* `align:center`.
~~~~html
    <form method="POST" id="piLoginForm" name="piLoginForm">
        
                    <label>
                <input id="otp" type="password" name="challenge" placeholder="OTP" autocomplete="off" autocorrect="off"
                       required autofocus style="width:230px; align:center; text-align:center; margin:0 0 5px">
            </label>
            <input id="submitButton" type="submit" class="button" value="Bestätigen" style="width:251px; margin:0 224px">
        
        <!-- Hidden input which store the info about changes -->
        <input id="modeChanged" type="hidden" name="modeChanged" value="0"/>
~~~~

**Comment by cornelinux** [comment]
Looks like here https://github.com/privacyidea/privacyidea-owncloud-app/blob/6616f5632f68b01fb9c7bbac74e59fb3932091f1/twofactor_privacyidea/templates/challenge.php#L31

the input field has a destinct stlye (with center) and the submitButton has not.
I would recommend using CSS anyways.

**Comment by lukasmatusiewicz** [comment]
PR with fix:
#88
