### ISSUE TITLE
WebAuthn image - no image

### ISSUE THREAD

**Issue by georgezip** [privacyidea/privacyidea-owncloud-app#99]
owncloud 10.11
newest version of privacyidea owncloud app

<img src="static/img/FIDO-U2F-Security-Key-444x444.png" style="text-align:center" alt="WebAuthn image">

is not loading on privacyidea webauth login screen

![Zrzut ekranu 2023-03-20 143558](https://user-images.githubusercontent.com/2536361/226356195-103dc61c-ff76-4602-af5a-99d232f648e1.png)
![Zrzut ekranu 2023-03-20 143541](https://user-images.githubusercontent.com/2536361/226356201-4395861c-8cf2-4bff-a9bf-c072afc26386.png)

**Comment by lukasmatusiewicz** [comment]
This problem is already known. A proper fix should be released with the privacyIDEA v3.9.
https://github.com/privacyidea/privacyidea/issues/3450
